Web3id revision
Concordium/concordium-rust-sdk pull request #104
Opened 2023-07-15 20:39 UTC by abizjak

## Purpose

Revise CIS4 client and Web3ID related functionality to new notion of credentials, registry contracts without storage.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2023-07-20 11:56 UTC, eb-concordium approved these changes

2023-07-20 12:01 UTC, annenkov requested changes

2023-07-31 18:50 UTC, abizjak commented on src/cis4.rs
> +        self.update_raw(signer, metadata, "revokeCredentialRevoker", parameter)
I have renamed the function as `revoke_credential_other`.

2023-07-31 18:55 UTC, abizjak commented on src/cis4.rs
>  }
Should be updated now.

2023-07-31 19:04 UTC, abizjak commented on src/web3id.rs
> +            let commitments = CredentialsInputs::Web3 { issuer_pk };
Renamed to `inputs`.

2023-08-01 09:14 UTC, annenkov commented on src/cis4.rs
> +    /// The extra nonce that must be provided is the nonce associatedw with the
```suggestion
    /// The extra nonce that must be provided is the nonce associated with the
```

2023-08-01 09:31 UTC, merged